WHITESPACE = _{ " " | "\r" | "\n" | "\t" }
COMMENT = _{ ";"+ ~ (!"\n" ~ ANY)* }

// Special Cases
defun = { "(" ~ "define-fun" ~ atom ~ list ~ ty ~ sexp ~ ")" }
sampleid = { "(" ~ "sample-id" ~ stringlit ~ stringlit ~ stringlit ~ ")" }

define_package_invariant = { "(" ~ "define-package-invariant" ~ sexp ~ ")" }
define_game_invariant = { "(" ~ "define-game-invariant" ~ sexp ~ ")" }
define_state_relation = { "(" ~ "define-state-relation" ~ atom ~ list ~ sexp ~ ")" }
define_lemma =          { "(" ~ "define-lemma" ~ atom ~ list ~ sexp ~ ")" }

// Fallback Entries
atom = @{ ( ASCII_ALPHA | "_" | "-" | "=" | "<" | ">" | "$" | "!" | "+" | "@" | "." | "*" ) ~ ( ASCII_ALPHA | ASCII_DIGIT | "_" | "-" | "=" | "<" | ">" | "$" | "!" | "+" | "@" | "." | "*" )* }
stringlit = _{ "\"" ~ string ~ "\"" }
string = { (!"\"" ~ ANY)* }

boolean = { "true" | "false" }
integer = @{"-"? ~ ASCII_DIGIT+ }
ty = { "Int" | "Bool" | sexp }
list = { "(" ~ sexp*~ ")" }

// Big Or, Fallback Entries last!
sexp = _{ sampleid | list | integer | boolean | stringlit | atom }

stmt = { defun | define_game_invariant | define_package_invariant | define_state_relation | define_lemma | sexp }
stmts = { SOI ~ stmt+ ~ EOI }
stmtlist = { "(" ~ stmt+ ~ ")" }

