[assumptions]
[assumptions.PRF]
left = "PRF_real"
right = "PRF_ideal"


[[game_hops]]
[game_hops.Reduction]

left = "SNPRF_real"
right = "SNPRF_g1"
assumption = "PRF"
leftmap = [["keys_top", "keys_top"], ["keys_bottom", "keys_bottom"],["prf","prf_top"]]
rightmap = [["keys_top", "keys_top"], ["keys_bottom", "keys_bottom"],["prf","prf_top"]]
