(* games/MediumComposition.ec for theorem `Proof`, composition `MediumComposition` — generated by `domino easycrypt`. *)

require import AllCore Distr FMap Int IntDiv Types.
require Interfaces Rand Fwd_v1.

clone Rand as Pkg_Rand.

clone Fwd_v1 as Pkg_Fwd.

module Inst_Fwd = Pkg_Fwd.Fwd_v1(Pkg_Rand.Rand).

module Game_MediumComposition : Interfaces.Iface_SmallComposition = {
  var abort_flag : bool

  proc init() : unit = {
    abort_flag <- false;
    Pkg_Rand.Rand.init();
    Inst_Fwd.init();
  }

  proc d_UsefulOracle() : (int * bits_n) option = {
    var ec_result : (int * bits_n) option <- None<:(int * bits_n)>;
    if (!abort_flag) {
      ec_result <@ Inst_Fwd.d_UsefulOracle();
      if (ec_result = None<:(int * bits_n)>) {
        abort_flag <- true;
      }
    }
    return ec_result;
  }
}.

module Exp_MediumComposition (A : Interfaces.Adv_SmallComposition) = {
  proc run() : bool = {
    var b' : bool;
    Game_MediumComposition.init();
    b' <@ A(Game_MediumComposition).run();
    return b';
  }
}.
