(* Types.ec for theorem `Simple4WHS` — generated by `domino easycrypt`. *)

require import AllCore Distr FMap Int IntDiv.

type bits_n.

op zero_n : bits_n.

op one_n : bits_n.

op dbits_n : bits_n distr.

axiom dbits_n_ll : is_lossless dbits_n.

op func_mac : bits_n -> bits_n -> int -> bits_n.

op func_prf : bits_n -> (int * int * bits_n * bits_n * bool) -> bits_n.
