(* games/Hybrid2.ec for theorem `Simple4WHS`, composition `Hybrid2` — generated by `domino easycrypt`. *)

require import AllCore Distr FMap Int IntDiv Types.
require Interfaces M_PRF Prot_NoPrf KX_NoPrf.

clone M_PRF as Pkg_Prf.

clone Prot_NoPrf as Pkg_Prot.

clone KX_NoPrf as Pkg_KX.

module Inst_Prot = Pkg_Prot.Prot_NoPrf(Pkg_Prf.M_PRF).

module Inst_KX = Pkg_KX.KX_NoPrf(Inst_Prot, Pkg_Prf.M_PRF).

module Game_Hybrid2 : Interfaces.Iface_Hybrid0 = {
  var abort_flag : bool

  proc init(b : bool, bprf : bool) : unit = {
    abort_flag <- false;
    Pkg_Prf.M_PRF.init(bprf);
    Inst_KX.init(b);
  }

  proc d_NewKey(ltk : bits_n option) : int option = {
    var ec_result : int option <- None<:int>;
    if (!abort_flag) {
      ec_result <@ Pkg_Prf.M_PRF.d_NewKey(ltk);
      if (ec_result = None<:int>) {
        abort_flag <- true;
      }
    }
    return ec_result;
  }

  proc d_NewSession(d_U : int, u : bool, d_V : int, kid : int) : int option = {
    var ec_result : int option <- None<:int>;
    if (!abort_flag) {
      ec_result <@ Inst_KX.d_NewSession(d_U, u, d_V, kid);
      if (ec_result = None<:int>) {
        abort_flag <- true;
      }
    }
    return ec_result;
  }

  proc d_Send1(ctr : int) : bits_n option = {
    var ec_result : bits_n option <- None<:bits_n>;
    if (!abort_flag) {
      ec_result <@ Inst_KX.d_Send1(ctr);
      if (ec_result = None<:bits_n>) {
        abort_flag <- true;
      }
    }
    return ec_result;
  }

  proc d_Send2(ctr : int, msg : bits_n) : (bits_n * bits_n) option = {
    var ec_result : (bits_n * bits_n) option <- None<:(bits_n * bits_n)>;
    if (!abort_flag) {
      ec_result <@ Inst_KX.d_Send2(ctr, msg);
      if (ec_result = None<:(bits_n * bits_n)>) {
        abort_flag <- true;
      }
    }
    return ec_result;
  }

  proc d_Send3(ctr : int, msg : (bits_n * bits_n)) : (bits_n * bits_n) option = {
    var ec_result : (bits_n * bits_n) option <- None<:(bits_n * bits_n)>;
    if (!abort_flag) {
      ec_result <@ Inst_KX.d_Send3(ctr, msg);
      if (ec_result = None<:(bits_n * bits_n)>) {
        abort_flag <- true;
      }
    }
    return ec_result;
  }

  proc d_Send4(ctr : int, msg : (bits_n * bits_n)) : bits_n option = {
    var ec_result : bits_n option <- None<:bits_n>;
    if (!abort_flag) {
      ec_result <@ Inst_KX.d_Send4(ctr, msg);
      if (ec_result = None<:bits_n>) {
        abort_flag <- true;
      }
    }
    return ec_result;
  }

  proc d_Send5(ctr : int, msg : bits_n) : bool option = {
    var ec_result : bool option <- None<:bool>;
    if (!abort_flag) {
      ec_result <@ Inst_KX.d_Send5(ctr, msg);
      if (ec_result = None<:bool>) {
        abort_flag <- true;
      }
    }
    return ec_result;
  }

  proc d_Reveal(ctr : int) : bits_n option = {
    var ec_result : bits_n option <- None<:bits_n>;
    if (!abort_flag) {
      ec_result <@ Inst_KX.d_Reveal(ctr);
      if (ec_result = None<:bits_n>) {
        abort_flag <- true;
      }
    }
    return ec_result;
  }

  proc d_Test(ctr : int) : bits_n option = {
    var ec_result : bits_n option <- None<:bits_n>;
    if (!abort_flag) {
      ec_result <@ Inst_KX.d_Test(ctr);
      if (ec_result = None<:bits_n>) {
        abort_flag <- true;
      }
    }
    return ec_result;
  }
}.

module Exp_Hybrid2 (A : Interfaces.Adv_Hybrid0) = {
  proc run(b : bool, bprf : bool) : bool = {
    var b' : bool;
    Game_Hybrid2.init(b, bprf);
    b' <@ A(Game_Hybrid2).run();
    return b';
  }
}.
