(* games/PRF_Game.ec for theorem `Simple4WHS`, composition `PRF` — generated by `domino easycrypt`. *)

require import AllCore Distr FMap Int IntDiv Types.
require Interfaces M_PRF.

clone M_PRF as Pkg_M_PRF.

module Game_PRF_Game : Interfaces.Iface_PRF_Game = {
  var abort_flag : bool

  proc init(b : bool) : unit = {
    abort_flag <- false;
    Pkg_M_PRF.M_PRF.init(b);
  }

  proc d_NewKey(ltk : bits_n option) : int option = {
    var ec_result : int option <- None<:int>;
    if (!abort_flag) {
      ec_result <@ Pkg_M_PRF.M_PRF.d_NewKey(ltk);
      if (ec_result = None<:int>) {
        abort_flag <- true;
      }
    }
    return ec_result;
  }

  proc d_Eval(kid : int, x : (int * int * bits_n * bits_n * bool)) : bits_n option = {
    var ec_result : bits_n option <- None<:bits_n>;
    if (!abort_flag) {
      ec_result <@ Pkg_M_PRF.M_PRF.d_Eval(kid, x);
      if (ec_result = None<:bits_n>) {
        abort_flag <- true;
      }
    }
    return ec_result;
  }

  proc d_Hon(kid : int) : bool option = {
    var ec_result : bool option <- None<:bool>;
    if (!abort_flag) {
      ec_result <@ Pkg_M_PRF.M_PRF.d_Hon(kid);
      if (ec_result = None<:bool>) {
        abort_flag <- true;
      }
    }
    return ec_result;
  }
}.

module Exp_PRF_Game (A : Interfaces.Adv_PRF_Game) = {
  proc run(b : bool) : bool = {
    var b' : bool;
    Game_PRF_Game.init(b);
    b' <@ A(Game_PRF_Game).run();
    return b';
  }
}.
