[assumptions]
[assumptions.LeftRight]
left = "Left"
right = "Right"

[[game_hops]]
[game_hops.Reduction]

left = "Left"
right = "Right"
assumption = "LeftRight"
leftmap = [["keys_top", "keys_top"], ["keys_bottom", "keys_bottom"],["gate","gate"], ["enc", "enc"]]
rightmap = [["keys_top", "keys_top"], ["keys_bottom", "keys_bottom"],["simgate", "simgate"],["ev", "ev"]]

[[game_hops]]
[game_hops.Equivalence]

left = "Left"
right = "Right"
invariant_path = "./invariant-GBLG.smt2"
trees.SETBIT = [ ["invariant-SETBIT-post", []]
             ]
trees.GBLG = [ ["right-all-aborts", []],
               ["right-all-aborts-inverse", []],
               ["left-all-aborts", []],
               ["left-inverse-all-aborts", []],
               ["aborts-equal", ["left-all-aborts","left-inverse-all-aborts","right-all-aborts","right-all-aborts-inverse"]],
               ["top-whole-left-neu-right-neu", ["no-abort","left-inverse-all-aborts","right-all-aborts-inverse",]],
               ["bot-left-neu",["no-abort","left-all-aborts","left-inverse-all-aborts"]],
               ["bot-right-neu",["no-abort","right-all-aborts","right-all-aborts-inverse"]],
               ["temp",["no-abort","left-all-aborts","left-inverse-all-aborts","right-all-aborts","right-all-aborts-inverse","bot-left-neu","bot-right-neu"]],
               ["same-output", ["temp","no-abort","left-all-aborts","left-inverse-all-aborts","right-all-aborts","right-all-aborts-inverse","bot-left-neu","bot-right-neu"]],
               ["invariant-GBLG-post", ["temp","no-abort","left-all-aborts","left-inverse-all-aborts","right-all-aborts","right-all-aborts-inverse","bot-left-neu","bot-right-neu"]]
             ]
