[assumptions]
[assumptions.LeftRight]
left = "Left"
right = "Right"

[[game_hops]]
[game_hops.Reduction]

left = "Left"
right = "Right"
assumption = "LeftRight"
leftmap = [["keys_top", "keys_top"], ["keys_bottom", "keys_bottom"],["gate","gate"], ["enc", "enc"]]
rightmap = [["keys_top", "keys_bottom"], ["keys_bottom", "keys_top"],["simgate", "simgate"],["ev", "ev"]]

[[game_hops]]
[game_hops.Equivalence]

left = "Left"
right = "Right"
invariant_path = "./invariant-GBLG.smt2"
trees.GBLG = [ ["lemma1-right-keys", []], 
               ["lemma1-left-keys", []], 
               ["lemma1-keys", ["lemma1-left-keys","lemma1-left-keys"]],
               ["lemma2-right-keys-a",[]],
               ["lemma2-left-keys-a",[]],
               ["lemma2-right-keys-b",["lemma2-right-keys-a"]],
               ["lemma2-left-keys-b",["lemma2-left-keys-a"]],
               ["lemma2-keys",["lemma2-left-keys-b","lemma2-right-keys-b"]]
             ]