[assumptions]
[assumptions.LeftRight]
left = "Left"
right = "Right"

[[game_hops]]

[game_hops.Reduction]

left = "Left"
right = "Right"
assumption = "LeftRight"
leftmap = [["keys_top", "keys_top"], ["keys_bottom", "keys_bottom"]]
rightmap = [["keys_top", "keys_top"], ["keys_bottom", "keys_bottom"]]

#[[game_hops]]
#
#[game_hops.Equivalence]
#
#left = "Asd"
#right = "rte"
#invariant_path = "s;lvksf"
    
