// SPDX-License-Identifier: MIT OR Apache-2.0

//! The EasyCrypt AST.
//!
//! This models EasyCrypt syntax, not Domino. It is the contract for the whole
//! `easycrypt` export epic: later stories translate Domino into this tree, and
//! [`super::render`] turns the tree into text. Nothing outside this epic should
//! ever build EasyCrypt source by formatting strings directly.
//!
//! There is deliberately no `Raw` variant anywhere in [`EcExpr`], [`EcStmt`] or
//! [`EcType`] — [`EcLemma::proof`] is the one place raw text is allowed, since
//! tactic scripts are not modelled. If a later story needs a construct that
//! does not exist here yet, it adds a variant instead of falling back to text.

#[derive(Debug, Clone, PartialEq, Default)]
pub struct EcFile {
    /// `(* generated by domino … *)` banner, rendered first.
    pub header: Vec<String>,
    pub requires: Vec<Require>,
    pub items: Vec<EcItem>,
}

/// `require [import] A B.`
#[derive(Debug, Clone, PartialEq)]
pub struct Require {
    pub import: bool,
    pub names: Vec<String>,
}

#[derive(Debug, Clone, PartialEq)]
pub enum EcItem {
    Comment(String),
    /// `type bits_n.`
    TypeAbstract { name: String },
    TypeAlias { name: String, ty: EcType },
    Record { name: String, fields: Vec<(String, EcType)> },
    /// `op zero_n : bits_n.`
    OpDecl { name: String, ty: EcType },
    OpDef {
        name: String,
        args: Vec<(String, EcType)>,
        ret: Option<EcType>,
        body: EcExpr,
    },
    Axiom { name: String, formula: EcExpr },
    /// A plain module type has `includes` empty and lists its own `procs`.
    /// `module type X = { include Y }.` (story 11) is `includes: vec![Y]`
    /// with `procs` empty — `module type X = Y.` is a parse error in
    /// EasyCrypt, so this is the only alias form available. A module type
    /// that both includes another and declares its own procs is not
    /// produced by anything in this epic yet.
    ModuleType {
        name: String,
        params: Vec<(String, String)>,
        includes: Vec<String>,
        procs: Vec<ProcSig>,
    },
    Clone {
        base: String,
        as_name: String,
        overrides: Vec<CloneOverride>,
    },
    /// `module M = F(A, B).`
    ModuleAlias {
        name: String,
        functor: String,
        args: Vec<String>,
    },
    Module(EcModule),
    Section(EcSection),
}

#[derive(Debug, Clone, PartialEq)]
pub enum CloneOverride {
    Type { lhs: String, rhs: EcType },
    Op { lhs: String, rhs: EcExpr },
}

#[derive(Debug, Clone, PartialEq)]
pub struct ProcSig {
    pub name: String,
    pub args: Vec<(String, EcType)>,
    pub ret: EcType,
}

#[derive(Debug, Clone, PartialEq)]
pub struct EcModule {
    pub name: String,
    /// Functor parameters: `(P : Prot_i)`.
    pub params: Vec<(String, String)>,
    /// `: KX_i` — checked structurally by EasyCrypt.
    pub implements: Option<String>,
    pub vars: Vec<(String, EcType)>,
    pub procs: Vec<EcProc>,
}

#[derive(Debug, Clone, PartialEq)]
pub struct EcProc {
    pub name: String,
    pub args: Vec<(String, EcType)>,
    pub ret: EcType,
    /// `var x : t;` or `var x <- e;` (EasyCrypt infers the type in the second
    /// form — always render the type as well, it costs nothing and reads
    /// better).
    pub locals: Vec<(String, EcType, Option<EcExpr>)>,
    pub body: EcBlock,
    /// The single trailing `return e;`.
    pub ret_expr: Option<EcExpr>,
}

#[derive(Debug, Clone, PartialEq, Default)]
pub struct EcBlock(pub Vec<EcStmt>);

#[derive(Debug, Clone, PartialEq)]
pub enum EcStmt {
    Comment(String),
    /// `x <- e;`
    Assign { lhs: EcLvalue, rhs: EcExpr },
    /// `x <$ d;`
    Sample { lhs: EcLvalue, distr: EcExpr },
    /// `r <@ M.p(a);`
    Call {
        lhs: Option<EcLvalue>,
        module: String,
        proc: String,
        args: Vec<EcExpr>,
    },
    If {
        cond: EcExpr,
        then_block: EcBlock,
        else_block: Option<EcBlock>,
    },
}

#[derive(Debug, Clone, PartialEq)]
pub enum EcLvalue {
    Var(String),
    /// `(a, b) <- e;`
    Tuple(Vec<String>),
    /// `m.[k] <- v;` — only legal when `m` is a program variable of `fmap`
    /// type.
    MapSet { map: String, key: EcExpr },
}

#[derive(Debug, Clone, PartialEq)]
pub enum EcExpr {
    Var(String),
    /// Qualified: `Pkg_KX.KX.ltk_map`, or a memory-tagged one in a formula,
    /// `M.x{1}`.
    Qualified { path: Vec<String>, mem: Option<u8> },
    Int(i64),
    Bool(bool),
    Unit,
    Tuple(Vec<EcExpr>),
    /// `` e.`1 `` — 1-based, as EasyCrypt counts.
    Proj { expr: Box<EcExpr>, index: usize },
    /// `` e.`field `` for records.
    Field { expr: Box<EcExpr>, field: String },
    RecordLit { fields: Vec<(String, EcExpr)> },
    Some_(Box<EcExpr>),
    /// `None<:t>` — always annotated; bare `None` is ambiguous in most
    /// positions.
    None_(EcType),
    Oget(Box<EcExpr>),
    /// `m.[k]`
    MapGet { map: Box<EcExpr>, key: Box<EcExpr> },
    /// `m.[k <- v]`
    MapSet {
        map: Box<EcExpr>,
        key: Box<EcExpr>,
        value: Box<EcExpr>,
    },
    /// `rem m k`
    MapRem { map: Box<EcExpr>, key: Box<EcExpr> },
    MapEmpty,
    /// `func_prf a b`
    App { head: String, args: Vec<EcExpr> },
    Unop { op: EcUnop, arg: Box<EcExpr> },
    Binop {
        op: EcBinop,
        lhs: Box<EcExpr>,
        rhs: Box<EcExpr>,
    },
    If {
        cond: Box<EcExpr>,
        then_expr: Box<EcExpr>,
        else_expr: Box<EcExpr>,
    },
    Let {
        name: String,
        value: Box<EcExpr>,
        body: Box<EcExpr>,
    },
    Quant {
        kind: Quantifier,
        binders: Vec<(String, EcType)>,
        body: Box<EcExpr>,
    },
    /// `Pr[M.p(args) @ &mem : event]`. `module` is the (possibly
    /// functor-applied) qualified module path, spelled exactly as
    /// [`EcStmt::Call`]'s own `module` field already allows
    /// (`"Hybrid0.Exp_Hybrid0(A)"`) — not a separate applied-module AST, to
    /// match that established convention.
    Pr {
        module: String,
        proc: String,
        args: Vec<EcExpr>,
        memory: String,
        event: Box<EcExpr>,
    },
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EcUnop {
    Not,
    Neg,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EcBinop {
    Eq,
    Ne,
    And,
    Or,
    Xor,
    Implies,
    Lt,
    Le,
    Gt,
    Ge,
    Add,
    Sub,
    Mul,
    /// Renders as `%/` (`IntDiv`).
    Div,
    /// Renders as `%%` (`IntDiv`).
    Mod,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Quantifier {
    Forall,
    Exists,
}

#[derive(Debug, Clone, PartialEq)]
pub enum EcType {
    Int,
    Bool,
    Unit,
    Named(String),
    Tuple(Vec<EcType>),
    Option(Box<EcType>),
    Fmap(Box<EcType>, Box<EcType>),
    Distr(Box<EcType>),
    Fun(Box<EcType>, Box<EcType>),
}

#[derive(Debug, Clone, PartialEq)]
pub struct EcSection {
    pub declares: Vec<DeclareModule>,
    pub items: Vec<EcItem>,
    pub lemmas: Vec<EcLemma>,
}

/// `declare module A <: Adv { -Game_H.G, -Game_H.Pkg_KX.KX }.`
#[derive(Debug, Clone, PartialEq)]
pub struct DeclareModule {
    pub name: String,
    pub module_type: String,
    pub restrictions: Vec<String>,
}

#[derive(Debug, Clone, PartialEq)]
pub struct EcLemma {
    pub name: String,
    /// `&m (b : bool)` — memory binders first, rendered verbatim in order.
    pub binders: Vec<LemmaBinder>,
    pub statement: EcExpr,
    /// Proof script. **The one place raw text is allowed** — tactics are not
    /// modelled.
    pub proof: Vec<ProofLine>,
}

#[derive(Debug, Clone, PartialEq)]
pub enum LemmaBinder {
    Memory(String),
    Typed { name: String, ty: EcType },
}

/// `bullet` is `+`/`-`/`*` nesting depth handling; `text` is one tactic line.
#[derive(Debug, Clone, PartialEq)]
pub struct ProofLine {
    pub indent: usize,
    pub bullet: Option<char>,
    pub text: String,
}
