// SPDX-License-Identifier: MIT OR Apache-2.0

//! The EasyCrypt AST.
//!
//! This models EasyCrypt syntax, not Domino. It is the contract for the whole
//! `easycrypt` export epic: later stories translate Domino into this tree, and
//! [`super::render`] turns the tree into text. Nothing outside this epic should
//! ever build EasyCrypt source by formatting strings directly.
//!
//! There is deliberately no `Raw` variant anywhere in [`EcExpr`], [`EcStmt`] or
//! [`EcType`] — [`EcLemma::proof`] is the one place raw text is allowed, since
//! tactic scripts are not modelled. If a later story needs a construct that
//! does not exist here yet, it adds a variant instead of falling back to text.

#[derive(Debug, Clone, PartialEq, Default)]
pub struct EcFile {
    /// `(* generated by domino … *)` banner, rendered first.
    pub header: Vec<String>,
    pub requires: Vec<Require>,
    pub items: Vec<EcItem>,
}

/// `require [import] A B.`
#[derive(Debug, Clone, PartialEq)]
pub struct Require {
    pub import: bool,
    pub names: Vec<String>,
}

#[derive(Debug, Clone, PartialEq)]
pub enum EcItem {
    Comment(String),
    /// `type bits_n.`
    TypeAbstract { name: String },
    TypeAlias { name: String, ty: EcType },
    Record { name: String, fields: Vec<(String, EcType)> },
    /// `op zero_n : bits_n.`
    OpDecl { name: String, ty: EcType },
    OpDef {
        name: String,
        args: Vec<(String, EcType)>,
        ret: Option<EcType>,
        body: EcExpr,
    },
    Axiom { name: String, formula: EcExpr },
    /// A plain module type has `includes` empty and lists its own `procs`.
    /// `module type X = { include Y }.` (story 11) is `includes: vec![Y]`
    /// with `procs` empty — `module type X = Y.` is a parse error in
    /// EasyCrypt, so this is the only alias form available. A module type
    /// that both includes another and declares its own procs is not
    /// produced by anything in this epic yet.
    ModuleType {
        name: String,
        params: Vec<(String, String)>,
        includes: Vec<String>,
        procs: Vec<ProcSig>,
    },
    Clone {
        base: String,
        as_name: String,
        overrides: Vec<CloneOverride>,
    },
    /// `module M = F(A, B).`
    ModuleAlias {
        name: String,
        functor: String,
        args: Vec<String>,
    },
    Module(EcModule),
    Section(EcSection),
}

#[derive(Debug, Clone, PartialEq)]
pub enum CloneOverride {
    Type { lhs: String, rhs: EcType },
    Op { lhs: String, rhs: EcExpr },
}

#[derive(Debug, Clone, PartialEq)]
pub struct ProcSig {
    pub name: String,
    pub args: Vec<(String, EcType)>,
    pub ret: EcType,
}

#[derive(Debug, Clone, PartialEq)]
pub struct EcModule {
    pub name: String,
    /// Functor parameters: `(P : Prot_i)`.
    pub params: Vec<(String, String)>,
    /// `: KX_i` — checked structurally by EasyCrypt.
    pub implements: Option<String>,
    pub vars: Vec<(String, EcType)>,
    pub procs: Vec<EcProc>,
}

#[derive(Debug, Clone, PartialEq)]
pub struct EcProc {
    pub name: String,
    pub args: Vec<(String, EcType)>,
    pub ret: EcType,
    /// `var x : t;` or `var x <- e;` (EasyCrypt infers the type in the second
    /// form — always render the type as well, it costs nothing and reads
    /// better).
    pub locals: Vec<(String, EcType, Option<EcExpr>)>,
    pub body: EcBlock,
    /// The single trailing `return e;`.
    pub ret_expr: Option<EcExpr>,
}

#[derive(Debug, Clone, PartialEq, Default)]
pub struct EcBlock(pub Vec<EcStmt>);

#[derive(Debug, Clone, PartialEq)]
pub enum EcStmt {
    Comment(String),
    /// `x <- e;`
    Assign { lhs: EcLvalue, rhs: EcExpr },
    /// `x <$ d;`
    Sample { lhs: EcLvalue, distr: EcExpr },
    /// `r <@ M.p(a);`
    Call {
        lhs: Option<EcLvalue>,
        module: String,
        proc: String,
        args: Vec<EcExpr>,
    },
    If {
        cond: EcExpr,
        then_block: EcBlock,
        else_block: Option<EcBlock>,
    },
}

#[derive(Debug, Clone, PartialEq)]
pub enum EcLvalue {
    Var(String),
    /// `(a, b) <- e;`
    Tuple(Vec<String>),
    /// `m.[k] <- v;` — only legal when `m` is a program variable of `fmap`
    /// type.
    MapSet { map: String, key: EcExpr },
}

#[derive(Debug, Clone, PartialEq)]
pub enum EcExpr {
    Var(String),
    /// Qualified: `Pkg_Inst_KX.ltk_map`, or a memory-tagged one in a formula,
    /// `M.x{1}`.
    Qualified { path: Vec<String>, mem: Option<u8> },
    Int(i64),
    Bool(bool),
    Unit,
    Tuple(Vec<EcExpr>),
    /// `` e.`1 `` — 1-based, as EasyCrypt counts.
    Proj { expr: Box<EcExpr>, index: usize },
    /// `` e.`field `` for records.
    Field { expr: Box<EcExpr>, field: String },
    RecordLit { fields: Vec<(String, EcExpr)> },
    Some_(Box<EcExpr>),
    /// Renders as bare `None`, never `None<:t>` — every position the
    /// exporter emits `None` in is already constrained (a typed local or
    /// state variable, an `fmap` get comparison, inside a typed tuple, an
    /// `op` body with a declared result type), so EasyCrypt infers the type
    /// on its own; the annotation was pure noise (story 12). The `EcType` is
    /// kept on this node anyway — unused by the renderer — because story
    /// 08's lowering to the debugger IR (`src/debug/ir.rs`) needs to know
    /// the type of an abort value.
    None_(EcType),
    Oget(Box<EcExpr>),
    /// `m.[k]`
    MapGet { map: Box<EcExpr>, key: Box<EcExpr> },
    /// `m.[k <- v]`
    MapSet {
        map: Box<EcExpr>,
        key: Box<EcExpr>,
        value: Box<EcExpr>,
    },
    /// `rem m k`
    MapRem { map: Box<EcExpr>, key: Box<EcExpr> },
    MapEmpty,
    /// `func_prf a b`
    App { head: String, args: Vec<EcExpr> },
    Unop { op: EcUnop, arg: Box<EcExpr> },
    Binop {
        op: EcBinop,
        lhs: Box<EcExpr>,
        rhs: Box<EcExpr>,
    },
    If {
        cond: Box<EcExpr>,
        then_expr: Box<EcExpr>,
        else_expr: Box<EcExpr>,
    },
    Let {
        name: String,
        value: Box<EcExpr>,
        body: Box<EcExpr>,
    },
    Quant {
        kind: Quantifier,
        binders: Vec<(String, EcType)>,
        body: Box<EcExpr>,
    },
    /// `Pr[M.p(args) @ &mem : event]`. `module` is the (possibly
    /// functor-applied) qualified module path, spelled exactly as
    /// [`EcStmt::Call`]'s own `module` field already allows
    /// (`"Hybrid0.Exp_Hybrid0(A)"`) — not a separate applied-module AST, to
    /// match that established convention.
    Pr {
        module: String,
        proc: String,
        args: Vec<EcExpr>,
        memory: String,
        event: Box<EcExpr>,
    },
    /// `={glob M}` — the two runs' own copies of `M`'s glob state are equal.
    /// Only produced inside this epic's own `byequiv` induction-start
    /// precondition (story 13, [`ProofLine::ByequivPrecondition`]); a
    /// self-delimited primitive, atom precedence like every other one here.
    GlobEq(String),
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EcUnop {
    Not,
    Neg,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EcBinop {
    Eq,
    Ne,
    And,
    Or,
    Xor,
    Implies,
    Lt,
    Le,
    Gt,
    Ge,
    Add,
    Sub,
    Mul,
    /// Renders as `%/` (`IntDiv`).
    Div,
    /// Renders as `%%` (`IntDiv`).
    Mod,
}

impl EcExpr {
    /// `[a, b, c]` -> `a op (b op c)`; `None` for no operands. Right-nested
    /// because EasyCrypt's `/\`, `\/` and `=>` are right-associative (story
    /// 43 §3.1), so the chain renders without parentheses; it is also how
    /// SMT-LIB reads an n-ary `=>`. For the associative `/\` and `\/`, an
    /// operand that is itself an `op` chain is spliced in, so the whole
    /// conjunction is one flat chain, its operands in their given order.
    pub fn right_chain(op: EcBinop, operands: Vec<EcExpr>) -> Option<EcExpr> {
        let mut flat = Vec::with_capacity(operands.len());
        for e in operands {
            if matches!(op, EcBinop::And | EcBinop::Or) {
                push_chain_operands(op, e, &mut flat);
            } else {
                flat.push(e);
            }
        }
        flat.into_iter().rev().reduce(|acc, e| EcExpr::Binop {
            op,
            lhs: Box::new(e),
            rhs: Box::new(acc),
        })
    }
}

/// The operands of the `op` chain `e`, left to right, however it nests.
fn push_chain_operands(op: EcBinop, e: EcExpr, out: &mut Vec<EcExpr>) {
    match e {
        EcExpr::Binop { op: o, lhs, rhs } if o == op => {
            push_chain_operands(op, *lhs, out);
            push_chain_operands(op, *rhs, out);
        }
        e => out.push(e),
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Quantifier {
    Forall,
    Exists,
}

#[derive(Debug, Clone, PartialEq)]
pub enum EcType {
    Int,
    Bool,
    Unit,
    Named(String),
    Tuple(Vec<EcType>),
    Option(Box<EcType>),
    Fmap(Box<EcType>, Box<EcType>),
    Distr(Box<EcType>),
    Fun(Box<EcType>, Box<EcType>),
}

#[derive(Debug, Clone, PartialEq)]
pub struct EcSection {
    pub declares: Vec<DeclareModule>,
    pub items: Vec<EcItem>,
    pub lemmas: Vec<EcLemma>,
}

/// `declare module A <: Adv { -Game_H.G, -Game_H.Pkg_Inst_KX }.`
#[derive(Debug, Clone, PartialEq)]
pub struct DeclareModule {
    pub name: String,
    pub module_type: String,
    pub restrictions: Vec<String>,
}

#[derive(Debug, Clone, PartialEq)]
pub struct EcLemma {
    pub name: String,
    /// `&m (b : bool)` — memory binders first, rendered verbatim in order.
    pub binders: Vec<LemmaBinder>,
    pub statement: EcExpr,
    /// Proof script. **The one place raw text is allowed** — tactics are not
    /// modelled.
    pub proof: Vec<ProofLine>,
}

#[derive(Debug, Clone, PartialEq)]
pub enum LemmaBinder {
    Memory(String),
    Typed { name: String, ty: EcType },
}

/// One line (or, for [`ProofLine::ByequivPrecondition`] and
/// [`ProofLine::InvariantCall`], one structured multi-line tactic) of a
/// lemma's proof script.
#[derive(Debug, Clone, PartialEq)]
pub enum ProofLine {
    /// `bullet` is `+`/`-`/`*` nesting depth handling; `text` is one raw
    /// tactic line — the one place raw text is allowed
    /// ([`EcLemma::proof`]'s own doc comment), since tactic scripts are not
    /// modelled in general.
    Tactic {
        indent: usize,
        bullet: Option<char>,
        text: String,
    },
    /// The `byequiv` induction start's own relational precondition (story
    /// 13): `conjuncts` in the order they render, `={glob A}` first. Kept
    /// structured (a real `Vec<EcExpr>`, not pre-joined text with embedded
    /// newlines) so a later lowering (story 08) has the actual relational
    /// formula to read, not tactic text to re-parse. Renders as
    /// `byequiv\n  (: <c0>\n     /\ <c1>\n     ...\n     ==> _) => //.`
    /// ([`super::render::render_proof_line`]).
    ByequivPrecondition { conjuncts: Vec<EcExpr> },
    /// The invariant `call` (story 07): `call (: <inv>); last first.`, with
    /// `inv` the invariant applied to one game-state record literal per
    /// side. Kept structured so the renderer lays it out (story 43 §3.3):
    /// each argument on its own line, one record field per line
    /// ([`super::render::render_proof_line`]).
    InvariantCall { inv: EcExpr },
}
