// SPDX-License-Identifier: MIT OR Apache-2.0

//! Building `Types.ec` (§3.4): the per-theorem file that declares the bits
//! types, their constants and distributions, and the theorem's function
//! constants.

use std::collections::{BTreeMap, HashSet};

use miette::SourceSpan;

use crate::theorem::Theorem;
use crate::types::{CountSpec, Type, TypeKind};

use super::ast::{EcExpr, EcFile, EcItem, EcType, Require};
use super::types::{bits_suffix, bits_type_name, func_op_name, translate_type};
use super::EcExportError;

/// Theorem-level Domino constructs — `Theorem::consts`, and the union of a
/// theorem's game-instance types (`GameInstAux::types`, story 05 unions
/// these across `theorem.instances`) — carry no [`SourceSpan`] in Domino's
/// data model, unlike statements and package field declarations. `Types.ec`
/// errors therefore point at this zero-length placeholder rather than real
/// source. This is a real gap, not a dodge: nothing in this story's
/// acceptance criteria can trigger it (every type reachable from a
/// well-typed theorem's consts and game-instance types is representable
/// here), but a later story that makes this reachable from bad input should
/// thread a real span through instead.
fn theorem_level_span() -> SourceSpan {
    SourceSpan::from((0, 0))
}

/// Build `Types.ec` for `theorem`, given the union of `Type`s its game
/// instances mention (`GameInstAux::types`, unioned over `theorem.instances`
/// — the caller's job, since that union is a transform output this module
/// doesn't produce).
///
/// Emits, in this order and deterministically (both maps below are
/// `BTreeMap`s keyed by the emitted EasyCrypt name, never a `HashSet`
/// iterated directly): one `type`/`zero`/`one`/`dbits`/`dbits_ll` block per
/// distinct bits type, then one `op func_<name>` per theorem constant of
/// `Fn` type. Theorem constants of `Integer`/`Boolean` type are not declared
/// here (§3.4): width integers became types above, and the rest are lemma
/// binders for stories 04/07.
pub fn build_types_file(
    theorem: &Theorem<'_>,
    types: &HashSet<Type>,
) -> Result<EcFile, EcExportError> {
    let span = theorem_level_span();

    let mut items = Vec::new();
    for (name, count) in collect_bits_types(types) {
        items.extend(bits_type_items(&name, &count));
    }
    for (name, ty) in collect_fn_consts(&theorem.consts) {
        items.push(EcItem::OpDecl {
            name: func_op_name(&name),
            ty: translate_type(&ty, span)?,
        });
    }

    Ok(EcFile {
        header: vec![format!(
            "Types.ec for theorem `{}` — generated by `domino easycrypt`.",
            theorem.name
        )],
        requires: vec![Require {
            import: true,
            names: vec![
                "AllCore".to_string(),
                "Distr".to_string(),
                "FMap".to_string(),
                "Int".to_string(),
                "IntDiv".to_string(),
            ],
        }],
        items,
    })
}

/// Distinct bits types, keyed by their EasyCrypt type name so the result is
/// sorted and de-duplicated in one step. Two `Type`s that are not
/// structurally equal (e.g. the same theorem width reached through
/// different game instances) but name the same EasyCrypt type collapse to
/// one entry here — correctly, since the name is derived from the
/// underlying theorem const's identifier, so two `CountSpec`s naming the
/// same EasyCrypt type always denote the same width.
fn collect_bits_types(types: &HashSet<Type>) -> BTreeMap<String, CountSpec> {
    let mut out = BTreeMap::new();
    for ty in types {
        if let TypeKind::Bits(count) = ty.kind() {
            out.insert(bits_type_name(count), count.clone());
        }
    }
    out
}

/// Theorem constants of `Fn` type, keyed by their raw (pre-mangling) name.
fn collect_fn_consts(consts: &[(String, Type)]) -> BTreeMap<String, Type> {
    consts
        .iter()
        .filter_map(|(name, ty)| match ty.kind() {
            TypeKind::Fn(..) => Some((name.clone(), ty.clone())),
            _ => None,
        })
        .collect()
}

/// The `type`/`op zero`/`op one`/`op dbits`/`axiom dbits_ll` block for one
/// bits type (§3.4). `name` is already the full EasyCrypt type name
/// (`bits_n`, `bits_256`, `bits`); `count` gives the suffix for its
/// constants (`None` for `Bits(*)`, whose constants are bare `zero`/`one`/
/// `dbits`).
fn bits_type_items(name: &str, count: &CountSpec) -> Vec<EcItem> {
    let suffix = bits_suffix(count);
    let with_suffix = |base: &str| match &suffix {
        Some(s) => format!("{base}_{s}"),
        None => base.to_string(),
    };
    let zero = with_suffix("zero");
    let one = with_suffix("one");
    let dbits = with_suffix("dbits");

    vec![
        EcItem::TypeAbstract {
            name: name.to_string(),
        },
        EcItem::OpDecl {
            name: zero,
            ty: EcType::Named(name.to_string()),
        },
        EcItem::OpDecl {
            name: one,
            ty: EcType::Named(name.to_string()),
        },
        EcItem::OpDecl {
            name: dbits.clone(),
            ty: EcType::Distr(Box::new(EcType::Named(name.to_string()))),
        },
        EcItem::Axiom {
            name: format!("{dbits}_ll"),
            formula: EcExpr::App {
                head: "is_lossless".to_string(),
                args: vec![EcExpr::Var(dbits)],
            },
        },
    ]
}

#[cfg(test)]
mod tests {
    use std::path::{Path, PathBuf};

    use super::*;
    use crate::identifier::{
        pkg_ident::{PackageConstIdentifier, PackageIdentifier},
        Identifier,
    };
    use crate::project::{DirectoryFiles, DirectoryProject, Project};
    use crate::transforms::theorem_transforms::EquivalenceTransform;
    use crate::transforms::TheoremTransform;
    use crate::writers::easycrypt::render::render_file;

    // Builds `<width_name>` as a resolved theorem-const identifier wrapped
    // in the `Expression` a package const's `game_assignment` field expects,
    // so `CountSpec::resolved_suffix`/`bits_suffix` can walk through it
    // exactly as `type_extract`'s real output does.
    fn theorem_const_expr(name: &str) -> crate::expressions::Expression {
        use crate::expressions::{Expression, ExpressionKind};
        use crate::identifier::theorem_ident::{TheoremConstIdentifier, TheoremIdentifier};
        Expression::from_kind(ExpressionKind::Identifier(Identifier::TheoremIdentifier(
            TheoremIdentifier::Const(TheoremConstIdentifier {
                theorem_name: "T".to_string(),
                name: name.to_string(),
                ty: Type::integer(),
                inst_info: None,
            }),
        )))
    }

    fn bits_identifier(width_name: &str) -> CountSpec {
        CountSpec::Identifier(Box::new(Identifier::PackageIdentifier(
            PackageIdentifier::Const(PackageConstIdentifier {
                pkg_name: "Pkg".to_string(),
                name: width_name.to_string(),
                pkg_inst_name: None,
                ty: Type::integer(),
                game_assignment: Some(Box::new(theorem_const_expr(width_name))),
                game_inst_name: None,
                game_name: None,
                theorem_name: None,
            }),
        )))
    }

    fn theorem_const_fn(name: &str, args: Vec<Type>, ret: Type) -> (String, Type) {
        (name.to_string(), Type::fun(args, ret))
    }

    #[test]
    fn collects_one_block_per_distinct_bits_type() {
        let mut types = HashSet::new();
        types.insert(Type::bits(bits_identifier("n")));
        types.insert(Type::bits(bits_identifier("n"))); // same width again
        types.insert(Type::bits(CountSpec::Literal(256)));
        types.insert(Type::bits(CountSpec::Any));
        types.insert(Type::integer()); // not a bits type, ignored

        let collected = collect_bits_types(&types);
        assert_eq!(
            collected.keys().cloned().collect::<Vec<_>>(),
            vec!["bits".to_string(), "bits_256".to_string(), "bits_n".to_string()]
        );
    }

    #[test]
    fn collects_fn_consts_only() {
        let consts = vec![
            ("b".to_string(), Type::boolean()),
            ("n".to_string(), Type::integer()),
            theorem_const_fn("mac", vec![Type::integer()], Type::integer()),
            theorem_const_fn("prf", vec![Type::integer()], Type::integer()),
        ];
        let collected = collect_fn_consts(&consts);
        assert_eq!(
            collected.keys().cloned().collect::<Vec<_>>(),
            vec!["mac".to_string(), "prf".to_string()]
        );
    }

    #[test]
    fn bits_type_items_named_width() {
        let items = bits_type_items("bits_n", &bits_identifier("n"));
        assert_eq!(
            items,
            vec![
                EcItem::TypeAbstract {
                    name: "bits_n".to_string()
                },
                EcItem::OpDecl {
                    name: "zero_n".to_string(),
                    ty: EcType::Named("bits_n".to_string())
                },
                EcItem::OpDecl {
                    name: "one_n".to_string(),
                    ty: EcType::Named("bits_n".to_string())
                },
                EcItem::OpDecl {
                    name: "dbits_n".to_string(),
                    ty: EcType::Distr(Box::new(EcType::Named("bits_n".to_string())))
                },
                EcItem::Axiom {
                    name: "dbits_n_ll".to_string(),
                    formula: EcExpr::App {
                        head: "is_lossless".to_string(),
                        args: vec![EcExpr::Var("dbits_n".to_string())],
                    },
                },
            ]
        );
    }

    #[test]
    fn bits_type_items_any_width_has_no_suffix() {
        let items = bits_type_items("bits", &CountSpec::Any);
        assert_eq!(
            items,
            vec![
                EcItem::TypeAbstract {
                    name: "bits".to_string()
                },
                EcItem::OpDecl {
                    name: "zero".to_string(),
                    ty: EcType::Named("bits".to_string())
                },
                EcItem::OpDecl {
                    name: "one".to_string(),
                    ty: EcType::Named("bits".to_string())
                },
                EcItem::OpDecl {
                    name: "dbits".to_string(),
                    ty: EcType::Distr(Box::new(EcType::Named("bits".to_string())))
                },
                EcItem::Axiom {
                    name: "dbits_ll".to_string(),
                    formula: EcExpr::App {
                        head: "is_lossless".to_string(),
                        args: vec![EcExpr::Var("dbits".to_string())],
                    },
                },
            ]
        );
    }

    // --- golden files: real projects, run through the real transform ----------

    fn load_theorem_types(dir: &str, theorem_name: &str) -> (crate::theorem::Theorem<'static>, HashSet<Type>) {
        // Leaked so the `Theorem<'a>` this test returns can outlive the
        // `DirectoryFiles`/`DirectoryProject` it borrows from — fine for a
        // one-shot golden-file test.
        let files: &'static DirectoryFiles = Box::leak(Box::new(DirectoryFiles::load(Path::new(dir)).unwrap()));
        let project: &'static DirectoryProject = Box::leak(Box::new(
            DirectoryProject::load(PathBuf::from(dir), files).unwrap(),
        ));
        let theorem = project.get_theorem(theorem_name).unwrap();

        let (theorem, auxs) = EquivalenceTransform.transform_theorem(theorem).unwrap();
        let types: HashSet<Type> = auxs
            .iter()
            .flat_map(|(_, aux)| aux.types.iter().cloned())
            .collect();
        (theorem, types)
    }

    fn assert_golden(dir: &str, theorem_name: &str, golden_path: &str) {
        let (theorem, types) = load_theorem_types(dir, theorem_name);
        let file = build_types_file(&theorem, &types).unwrap();
        let rendered = render_file(&file);

        let full_path = format!(
            "{}/{golden_path}",
            concat!(env!("CARGO_MANIFEST_DIR"))
        );
        let expected = std::fs::read_to_string(&full_path)
            .unwrap_or_else(|e| panic!("failed to read golden file {full_path}: {e}"));
        assert_eq!(rendered, expected, "rendered Types.ec != {full_path}");
    }

    #[test]
    fn hello_world_types_file_matches_golden() {
        assert_golden(
            "example-projects/hello-world",
            "Proof",
            "testdata/easycrypt/story02/hello-world/Types.ec",
        );
    }

    #[test]
    fn simple_kem_example_types_file_matches_golden() {
        assert_golden(
            "example-projects/simple-KEM-example",
            "KEM_Proof",
            "testdata/easycrypt/story02/simple-KEM-example/Types.ec",
        );
    }

    #[test]
    fn simple_4whs_types_file_matches_golden() {
        assert_golden(
            "example-projects/4WHS",
            "Simple4WHS",
            "testdata/easycrypt/story02/4WHS/Types.ec",
        );
    }

    #[test]
    fn rendering_is_deterministic() {
        let (theorem, types) = load_theorem_types("example-projects/4WHS", "Simple4WHS");
        let a = render_file(&build_types_file(&theorem, &types).unwrap());
        let b = render_file(&build_types_file(&theorem, &types).unwrap());
        assert_eq!(a, b);
    }

    fn assert_compiles(dir: &str, file: &str) {
        let full_dir = format!("{}/{dir}", env!("CARGO_MANIFEST_DIR"));
        let full_file = format!("{full_dir}/{file}");
        crate::writers::easycrypt::test_support::assert_compiles(&full_dir, &full_file);
    }

    #[test]
    fn hello_world_types_file_compiles() {
        assert_compiles("testdata/easycrypt/story02/hello-world", "Types.ec");
    }

    #[test]
    fn simple_kem_example_types_file_compiles() {
        assert_compiles("testdata/easycrypt/story02/simple-KEM-example", "Types.ec");
    }

    #[test]
    fn simple_4whs_types_file_compiles() {
        assert_compiles("testdata/easycrypt/story02/4WHS", "Types.ec");
    }
}
