(* Comp_BigComposition.ec for theorem `Proof`, composition `BigComposition` — generated by `domino easycrypt`. *)

require import AllCore Distr FMap Int IntDiv Types.
require Interfaces Variant_Rand Variant_Fwd_v1 Variant_Fwd_v2.

clone Variant_Rand as Pkg_Rand.

clone Variant_Fwd_v1 as Pkg_Fwd.

clone Variant_Fwd_v2 as Pkg_Fwd2.

module Inst_Fwd = Pkg_Fwd.Fwd_v1(Pkg_Rand.Rand).

module Inst_Fwd2 = Pkg_Fwd2.Fwd_v2(Inst_Fwd).

module Game_BigComposition : Interfaces.Iface_MediumCompositionMoreOracles = {
  var abort_flag : bool

  proc init() : unit = {
    abort_flag <- false;
    Pkg_Rand.Rand.init();
    Inst_Fwd.init();
    Inst_Fwd2.init();
  }

  proc d_UsefulOracle() : (int * bits_n) option = {
    var ec_result : (int * bits_n) option <- None<:(int * bits_n)>;
    if (!abort_flag) {
      ec_result <@ Inst_Fwd2.d_UsefulOracle();
      if (ec_result = None<:(int * bits_n)>) {
        abort_flag <- true;
      }
    }
    return ec_result;
  }

  proc d_UselessOracle(x : int) : int option = {
    var ec_result : int option <- None<:int>;
    if (!abort_flag) {
      ec_result <@ Inst_Fwd2.d_UselessOracle(x);
      if (ec_result = None<:int>) {
        abort_flag <- true;
      }
    }
    return ec_result;
  }
}.

module Exp_BigComposition (A : Interfaces.Adv_MediumCompositionMoreOracles) = {
  proc run() : bool = {
    var b' : bool;
    Game_BigComposition.init();
    b' <@ A(Game_BigComposition).run();
    return b';
  }
}.
