(* Comp_SmallComposition.ec for theorem `Proof`, composition `SmallComposition` — generated by `domino easycrypt`. *)

require import AllCore Distr FMap Int IntDiv Types.
require Interfaces Pkg_Rand.

clone Pkg_Rand as Cloned_Pkg_Rand.

module Pkg_Inst_Rand = Cloned_Pkg_Rand.Rand.

module Game_SmallComposition : Interfaces.Iface_SmallComposition = {
  var abort_flag : bool

  proc init() : unit = {
    abort_flag <- false;
    Pkg_Inst_Rand.init();
  }

  proc d_UsefulOracle() : (int * bits_n) option = {
    var ec_result : (int * bits_n) option <- None;
    if (!abort_flag) {
      ec_result <@ Pkg_Inst_Rand.d_UsefulOracle();
      if (ec_result = None) {
        abort_flag <- true;
      }
    }
    return ec_result;
  }
}.

module Exp_SmallComposition (A : Interfaces.Adv_SmallComposition) = {
  proc run() : bool = {
    var b' : bool;
    Game_SmallComposition.init();
    b' <@ A(Game_SmallComposition).run();
    return b';
  }
}.
