(* Comp_MediumComposition.ec for theorem `Proof`, composition `MediumComposition` — generated by `domino easycrypt`. *)

require import AllCore Distr FMap Int IntDiv Types.
require Interfaces Pkg_Rand Pkg_Fwd.

clone Pkg_Rand as Cloned_Pkg_Rand.

clone Pkg_Fwd as Cloned_Pkg_Fwd.

module Pkg_Inst_Rand = Cloned_Pkg_Rand.Rand.

module Pkg_Inst_Fwd = Cloned_Pkg_Fwd.Fwd(Pkg_Inst_Rand).

module Game_MediumComposition : Interfaces.Iface_SmallComposition = {
  var abort_flag : bool

  proc init() : unit = {
    abort_flag <- false;
    Pkg_Inst_Rand.init();
    Pkg_Inst_Fwd.init();
  }

  proc d_UsefulOracle() : (int * bits_n) option = {
    var ec_result : (int * bits_n) option <- None;
    if (!abort_flag) {
      ec_result <@ Pkg_Inst_Fwd.d_UsefulOracle();
      if (ec_result = None) {
        abort_flag <- true;
      }
    }
    return ec_result;
  }
}.

module Exp_MediumComposition (A : Interfaces.Adv_SmallComposition) = {
  proc run() : bool = {
    var b' : bool;
    Game_MediumComposition.init();
    b' <@ A(Game_MediumComposition).run();
    return b';
  }
}.
