(* Comp_MediumCompositionMoreOracles.ec for theorem `Proof`, composition `MediumCompositionMoreOracles` — generated by `domino easycrypt`. *)

require import AllCore Distr FMap Int IntDiv Types.
require Interfaces Variant_Rand Variant_Fwd_v1.

clone Variant_Rand as Pkg_Rand.

clone Variant_Fwd_v1 as Pkg_Fwd.

module Inst_Fwd = Pkg_Fwd.Fwd_v1(Pkg_Rand.Rand).

module Game_MediumCompositionMoreOracles : Interfaces.Iface_MediumCompositionMoreOracles = {
  var abort_flag : bool

  proc init() : unit = {
    abort_flag <- false;
    Pkg_Rand.Rand.init();
    Inst_Fwd.init();
  }

  proc d_UsefulOracle() : (int * bits_n) option = {
    var ec_result : (int * bits_n) option <- None;
    if (!abort_flag) {
      ec_result <@ Inst_Fwd.d_UsefulOracle();
      if (ec_result = None) {
        abort_flag <- true;
      }
    }
    return ec_result;
  }

  proc d_UselessOracle(x : int) : int option = {
    var ec_result : int option <- None;
    if (!abort_flag) {
      ec_result <@ Inst_Fwd.d_UselessOracle(x);
      if (ec_result = None) {
        abort_flag <- true;
      }
    }
    return ec_result;
  }
}.

module Exp_MediumCompositionMoreOracles (A : Interfaces.Adv_MediumCompositionMoreOracles) = {
  proc run() : bool = {
    var b' : bool;
    Game_MediumCompositionMoreOracles.init();
    b' <@ A(Game_MediumCompositionMoreOracles).run();
    return b';
  }
}.
