(* Comp_BigComposition.ec for theorem `Proof`, composition `BigComposition` — generated by `domino easycrypt`. *)

require import AllCore Distr FMap Int IntDiv Types.
require Interfaces Pkg_Rand Pkg_Fwd.

clone Pkg_Rand as Cloned_Pkg_Rand.

clone Pkg_Fwd as Cloned_Pkg_Fwd.

clone Pkg_Fwd as Cloned_Pkg_Fwd2.

module Pkg_Inst_Rand = Cloned_Pkg_Rand.Rand.

module Pkg_Inst_Fwd = Cloned_Pkg_Fwd.Fwd(Pkg_Inst_Rand).

module Pkg_Inst_Fwd2 = Cloned_Pkg_Fwd2.Fwd(Pkg_Inst_Fwd).

module Game_BigComposition : Interfaces.Iface_MediumCompositionMoreOracles = {
  var abort_flag : bool

  proc init() : unit = {
    abort_flag <- false;
    Pkg_Inst_Rand.init();
    Pkg_Inst_Fwd.init();
    Pkg_Inst_Fwd2.init();
  }

  proc d_UsefulOracle() : (int * bits_n) option = {
    var ec_result : (int * bits_n) option <- None;
    if (!abort_flag) {
      ec_result <@ Pkg_Inst_Fwd2.d_UsefulOracle();
      if (ec_result = None) {
        abort_flag <- true;
      }
    }
    return ec_result;
  }

  proc d_UselessOracle(x : int) : int option = {
    var ec_result : int option <- None;
    if (!abort_flag) {
      ec_result <@ Pkg_Inst_Fwd2.d_UselessOracle(x);
      if (ec_result = None) {
        abort_flag <- true;
      }
    }
    return ec_result;
  }
}.

module Exp_BigComposition (A : Interfaces.Adv_MediumCompositionMoreOracles) = {
  proc run() : bool = {
    var b' : bool;
    Game_BigComposition.init();
    b' <@ A(Game_BigComposition).run();
    return b';
  }
}.
