(* Interfaces.ec for theorem `Proof` — generated by `domino easycrypt`. *)

require import AllCore FMap Distr Int Types.

module type Rand_i = {
  proc d_UsefulOracle() : (int * bits_n) option
  proc d_UselessOracle(x : int) : int option
}.

module type Fwd_v1_i = {
  proc d_UsefulOracle() : (int * bits_n) option
  proc d_UselessOracle(x : int) : int option
}.

module type Fwd_v2_i = {
  proc d_UsefulOracle() : (int * bits_n) option
  proc d_UselessOracle(x : int) : int option
}.

(* Iface_SmallComposition/Adv_SmallComposition also cover: MediumComposition *)

module type Iface_SmallComposition = {
  proc d_UsefulOracle() : (int * bits_n) option
}.

module type Adv_SmallComposition (O : Iface_SmallComposition) = {
  proc run() : bool
}.

(* Iface_MediumCompositionMoreOracles/Adv_MediumCompositionMoreOracles also cover: BigComposition *)

module type Iface_MediumCompositionMoreOracles = {
  proc d_UsefulOracle() : (int * bits_n) option
  proc d_UselessOracle(x : int) : int option
}.

module type Adv_MediumCompositionMoreOracles (O : Iface_MediumCompositionMoreOracles) = {
  proc run() : bool
}.
