(* Types.ec for theorem `Proof` — generated by `domino easycrypt`. *)

require import AllCore Distr FMap Int IntDiv.

type bits_n.

op zero_n : bits_n.

op one_n : bits_n.

op dbits_n : bits_n distr.

axiom dbits_n_ll : is_lossless dbits_n.
