(* generated by domino easycrypt exporter — story 01 kitchen sink *)

require import AllCore Bool Distr FMap IntDiv Base.

(* exercises every EcItem, EcStmt, EcExpr and EcType variant *)

type bits_n.

type pair_t = (int * bool).

type rec_t = {
  fld_a : int;
  fld_b : bool
}.

op zero_n : bits_n.

op dbits : bits_n distr.

op kitchen_fun_ty : (int -> int) -> int.

op idfun_helper (x : int) : int = x.

op mk_rec (a : int) (b : bool) : rec_t = {| fld_a = a; fld_b = b |}.

op kitchen_tuple_and_proj (s : (int * int)) : int = s.`1 + s.`2.

op kitchen_field (r : rec_t) : int = r.`fld_a.

op kitchen_option (x : int option) : int = oget x.

op kitchen_some : int option = Some 3.

op kitchen_none : int option = None<:int>.

op kitchen_map_get (m : (int, bool) fmap) (k : int) : bool option = m.[k].

op kitchen_map_set (m : (int, bool) fmap) (k : int) (v : bool) : (int, bool) fmap = m.[k <- v].

op kitchen_map_rem (m : (int, bool) fmap) (k : int) : (int, bool) fmap = rem m k.

op kitchen_map_empty : (int, bool) fmap = empty.

op kitchen_app (x : int) : int = idfun_helper x.

op kitchen_neg_lit : int = idfun_helper (-1).

op kitchen_unop (b : bool) : bool = !b.

op kitchen_neg (x : int) : int = -x.

op kitchen_bool_lit : bool = true.

op kitchen_unit : unit = tt.

op (>) (x : int) (y : int) : bool = y < x.

op (>=) (x : int) (y : int) : bool = y <= x.

op kitchen_cmp (a : int) (b : int) : bool = a = b /\ a <> b \/ (a < b) ^^ (a <= b) => a > b \/ a >= b.

op kitchen_arith (a : int) (b : int) : int = a + b - a * (b %/ (b + 1)) %% 2.

op kitchen_if (b : bool) (x : int) (y : int) : int = if b then x else y.

op kitchen_let (x : int) : int = let y = x + 1 in y * y.

op kitchen_quant : bool = forall (x : int), exists (y : int), x = y \/ x <> y.

op kitchen_qualified : int = Base.dummy.

axiom top_axiom : zero_n = zero_n.

module type Proto = {
  proc init(seed : int) : unit
}.

module type Adv (O : Proto) = {
  proc run() : bool
}.

clone Base as BaseInst with type t <- int, op dummy <- 3.

module Impl : Proto = {
  var st : int

  proc init(seed : int) : unit = {
    (* record the seed as our state *)
    st <- seed;
    return tt;
  }
}.

module Fctr (P : Proto) = {
  proc run() : unit = {
    P.init(0);
    return tt;
  }
}.

module Inst = Fctr(Impl).

module Stateful = {
  var tbl : (int, bool) fmap
  var ctr : int

  proc reset() : unit = {
    (* reset the table and counter *)
    tbl <- empty;
    ctr <- 0;
    return tt;
  }

  proc flip(k : int) : bool = {
    var cur : bool option;
    var result : bool;
    cur <- tbl.[k];
    if (cur = None<:bool>) {
      result <- true;
    } else {
      result <- !oget cur;
    }
    tbl.[k] <- result;
    ctr <- ctr + 1;
    return result;
  }

  proc sample_bit() : bits_n = {
    var x : bits_n;
    x <$ dbits;
    return x;
  }

  proc pair() : (int * int) = {
    var p : (int * int);
    var a : int <- 0;
    var b : int <- 0;
    (a, b) <- (ctr, ctr);
    p <- (a, b);
    return p;
  }
}.

module Caller = {
  proc call_flip(k : int) : bool = {
    var r : bool;
    r <@ Stateful.flip(k);
    return r;
  }
}.

section.

declare module A <: Proto { -Impl }.

axiom section_axiom : 1 = 1.

lemma typed_lemma (b : bool) : b \/ !b.
proof.
case: b.
+ trivial.
+ trivial.
qed.

lemma mem_tag_lemma &1 : Impl.st{1} = Impl.st{1}.
proof.
trivial.
qed.

end section.
