(* Comp_Hybrid2.ec for theorem `Simple4WHS`, composition `Hybrid2` — generated by `domino easycrypt`. *)

require import AllCore Distr FMap Int IntDiv Types.
require Interfaces Pkg_PRF Pkg_Prot_NoPrf Pkg_KX_NoPrf.

clone Pkg_PRF as Cloned_Pkg_Prf.

clone Pkg_Prot_NoPrf as Cloned_Pkg_Prot.

clone Pkg_KX_NoPrf as Cloned_Pkg_KX.

module Pkg_Inst_Prf = Cloned_Pkg_Prf.PRF.

module Pkg_Inst_Prot = Cloned_Pkg_Prot.Prot_NoPrf(Pkg_Inst_Prf).

module Pkg_Imports_KX : Pkg_KX_NoPrf.KX_NoPrf_Imports = {
  proc d_Eval(h : int, x : (int * int * bits_n * bits_n * bool)) : bits_n option = {
    var r : bits_n option;
    r <@ Pkg_Inst_Prf.d_Eval(h, x);
    return r;
  }

  proc d_Hon(h : int) : bool option = {
    var r : bool option;
    r <@ Pkg_Inst_Prf.d_Hon(h);
    return r;
  }

  proc d_Run1(state : (int * bool * int * int * bool option * bits_n option * bits_n option * bits_n option * (int * int * bits_n * bits_n * bits_n) option * int)) : ((int * bool * int * int * bool option * bits_n option * bits_n option * bits_n option * (int * int * bits_n * bits_n * bits_n) option * int) * bits_n) option = {
    var r : ((int * bool * int * int * bool option * bits_n option * bits_n option * bits_n option * (int * int * bits_n * bits_n * bits_n) option * int) * bits_n) option;
    r <@ Pkg_Inst_Prot.d_Run1(state);
    return r;
  }

  proc d_Run2(state : (int * bool * int * int * bool option * bits_n option * bits_n option * bits_n option * (int * int * bits_n * bits_n * bits_n) option * int), ni : bits_n) : ((int * bool * int * int * bool option * bits_n option * bits_n option * bits_n option * (int * int * bits_n * bits_n * bits_n) option * int) * (bits_n * bits_n)) option = {
    var r : ((int * bool * int * int * bool option * bits_n option * bits_n option * bits_n option * (int * int * bits_n * bits_n * bits_n) option * int) * (bits_n * bits_n)) option;
    r <@ Pkg_Inst_Prot.d_Run2(state, ni);
    return r;
  }

  proc d_Run3(state : (int * bool * int * int * bool option * bits_n option * bits_n option * bits_n option * (int * int * bits_n * bits_n * bits_n) option * int), msg : (bits_n * bits_n)) : ((int * bool * int * int * bool option * bits_n option * bits_n option * bits_n option * (int * int * bits_n * bits_n * bits_n) option * int) * (bits_n * bits_n)) option = {
    var r : ((int * bool * int * int * bool option * bits_n option * bits_n option * bits_n option * (int * int * bits_n * bits_n * bits_n) option * int) * (bits_n * bits_n)) option;
    r <@ Pkg_Inst_Prot.d_Run3(state, msg);
    return r;
  }

  proc d_Run4(state : (int * bool * int * int * bool option * bits_n option * bits_n option * bits_n option * (int * int * bits_n * bits_n * bits_n) option * int), msg : (bits_n * bits_n)) : ((int * bool * int * int * bool option * bits_n option * bits_n option * bits_n option * (int * int * bits_n * bits_n * bits_n) option * int) * bits_n) option = {
    var r : ((int * bool * int * int * bool option * bits_n option * bits_n option * bits_n option * (int * int * bits_n * bits_n * bits_n) option * int) * bits_n) option;
    r <@ Pkg_Inst_Prot.d_Run4(state, msg);
    return r;
  }

  proc d_Run5(state : (int * bool * int * int * bool option * bits_n option * bits_n option * bits_n option * (int * int * bits_n * bits_n * bits_n) option * int), tau : bits_n) : ((int * bool * int * int * bool option * bits_n option * bits_n option * bits_n option * (int * int * bits_n * bits_n * bits_n) option * int) * bool) option = {
    var r : ((int * bool * int * int * bool option * bits_n option * bits_n option * bits_n option * (int * int * bits_n * bits_n * bits_n) option * int) * bool) option;
    r <@ Pkg_Inst_Prot.d_Run5(state, tau);
    return r;
  }
}.

module Pkg_Inst_KX = Cloned_Pkg_KX.KX_NoPrf(Pkg_Imports_KX).

module Game_Hybrid2 : Interfaces.Iface_Hybrid0 = {
  var abort_flag : bool

  proc init(b : bool, bprf : bool) : unit = {
    abort_flag <- false;
    Pkg_Inst_Prf.init(bprf);
    Pkg_Inst_KX.init(b);
  }

  proc d_NewKey(ltk : bits_n option) : int option = {
    var ec_result : int option <- None;
    if (!abort_flag) {
      ec_result <@ Pkg_Inst_Prf.d_NewKey(ltk);
      if (ec_result = None) {
        abort_flag <- true;
      }
    }
    return ec_result;
  }

  proc d_NewSession(d_U : int, u : bool, d_V : int, kid : int) : int option = {
    var ec_result : int option <- None;
    if (!abort_flag) {
      ec_result <@ Pkg_Inst_KX.d_NewSession(d_U, u, d_V, kid);
      if (ec_result = None) {
        abort_flag <- true;
      }
    }
    return ec_result;
  }

  proc d_Send1(ctr : int) : bits_n option = {
    var ec_result : bits_n option <- None;
    if (!abort_flag) {
      ec_result <@ Pkg_Inst_KX.d_Send1(ctr);
      if (ec_result = None) {
        abort_flag <- true;
      }
    }
    return ec_result;
  }

  proc d_Send2(ctr : int, msg : bits_n) : (bits_n * bits_n) option = {
    var ec_result : (bits_n * bits_n) option <- None;
    if (!abort_flag) {
      ec_result <@ Pkg_Inst_KX.d_Send2(ctr, msg);
      if (ec_result = None) {
        abort_flag <- true;
      }
    }
    return ec_result;
  }

  proc d_Send3(ctr : int, msg : (bits_n * bits_n)) : (bits_n * bits_n) option = {
    var ec_result : (bits_n * bits_n) option <- None;
    if (!abort_flag) {
      ec_result <@ Pkg_Inst_KX.d_Send3(ctr, msg);
      if (ec_result = None) {
        abort_flag <- true;
      }
    }
    return ec_result;
  }

  proc d_Send4(ctr : int, msg : (bits_n * bits_n)) : bits_n option = {
    var ec_result : bits_n option <- None;
    if (!abort_flag) {
      ec_result <@ Pkg_Inst_KX.d_Send4(ctr, msg);
      if (ec_result = None) {
        abort_flag <- true;
      }
    }
    return ec_result;
  }

  proc d_Send5(ctr : int, msg : bits_n) : bool option = {
    var ec_result : bool option <- None;
    if (!abort_flag) {
      ec_result <@ Pkg_Inst_KX.d_Send5(ctr, msg);
      if (ec_result = None) {
        abort_flag <- true;
      }
    }
    return ec_result;
  }

  proc d_Reveal(ctr : int) : bits_n option = {
    var ec_result : bits_n option <- None;
    if (!abort_flag) {
      ec_result <@ Pkg_Inst_KX.d_Reveal(ctr);
      if (ec_result = None) {
        abort_flag <- true;
      }
    }
    return ec_result;
  }

  proc d_Test(ctr : int) : bits_n option = {
    var ec_result : bits_n option <- None;
    if (!abort_flag) {
      ec_result <@ Pkg_Inst_KX.d_Test(ctr);
      if (ec_result = None) {
        abort_flag <- true;
      }
    }
    return ec_result;
  }
}.

module Exp_Hybrid2 (A : Interfaces.Adv_Hybrid0) = {
  proc run(b : bool, bprf : bool) : bool = {
    var b' : bool;
    Game_Hybrid2.init(b, bprf);
    b' <@ A(Game_Hybrid2).run();
    return b';
  }
}.
