(* Comp_Hybrid0.ec for theorem `Simple4WHS`, composition `Hybrid0` — generated by `domino easycrypt`. *)

require import AllCore Distr FMap Int IntDiv Types.
require Interfaces Variant_Prot Variant_KX.

clone Variant_Prot as Pkg_Prot.

clone Variant_KX as Pkg_KX.

module Inst_KX = Pkg_KX.KX(Pkg_Prot.Prot).

module Game_Hybrid0 : Interfaces.Iface_Hybrid0 = {
  var abort_flag : bool

  proc init(b : bool) : unit = {
    abort_flag <- false;
    Inst_KX.init(b);
  }

  proc d_NewKey(ltk : bits_n option) : int option = {
    var ec_result : int option <- None;
    if (!abort_flag) {
      ec_result <@ Inst_KX.d_NewKey(ltk);
      if (ec_result = None) {
        abort_flag <- true;
      }
    }
    return ec_result;
  }

  proc d_NewSession(d_U : int, u : bool, d_V : int, kid : int) : int option = {
    var ec_result : int option <- None;
    if (!abort_flag) {
      ec_result <@ Inst_KX.d_NewSession(d_U, u, d_V, kid);
      if (ec_result = None) {
        abort_flag <- true;
      }
    }
    return ec_result;
  }

  proc d_Send1(ctr : int) : bits_n option = {
    var ec_result : bits_n option <- None;
    if (!abort_flag) {
      ec_result <@ Inst_KX.d_Send1(ctr);
      if (ec_result = None) {
        abort_flag <- true;
      }
    }
    return ec_result;
  }

  proc d_Send2(ctr : int, msg : bits_n) : (bits_n * bits_n) option = {
    var ec_result : (bits_n * bits_n) option <- None;
    if (!abort_flag) {
      ec_result <@ Inst_KX.d_Send2(ctr, msg);
      if (ec_result = None) {
        abort_flag <- true;
      }
    }
    return ec_result;
  }

  proc d_Send3(ctr : int, msg : (bits_n * bits_n)) : (bits_n * bits_n) option = {
    var ec_result : (bits_n * bits_n) option <- None;
    if (!abort_flag) {
      ec_result <@ Inst_KX.d_Send3(ctr, msg);
      if (ec_result = None) {
        abort_flag <- true;
      }
    }
    return ec_result;
  }

  proc d_Send4(ctr : int, msg : (bits_n * bits_n)) : bits_n option = {
    var ec_result : bits_n option <- None;
    if (!abort_flag) {
      ec_result <@ Inst_KX.d_Send4(ctr, msg);
      if (ec_result = None) {
        abort_flag <- true;
      }
    }
    return ec_result;
  }

  proc d_Send5(ctr : int, msg : bits_n) : bool option = {
    var ec_result : bool option <- None;
    if (!abort_flag) {
      ec_result <@ Inst_KX.d_Send5(ctr, msg);
      if (ec_result = None) {
        abort_flag <- true;
      }
    }
    return ec_result;
  }

  proc d_Reveal(ctr : int) : bits_n option = {
    var ec_result : bits_n option <- None;
    if (!abort_flag) {
      ec_result <@ Inst_KX.d_Reveal(ctr);
      if (ec_result = None) {
        abort_flag <- true;
      }
    }
    return ec_result;
  }

  proc d_Test(ctr : int) : bits_n option = {
    var ec_result : bits_n option <- None;
    if (!abort_flag) {
      ec_result <@ Inst_KX.d_Test(ctr);
      if (ec_result = None) {
        abort_flag <- true;
      }
    }
    return ec_result;
  }
}.

module Exp_Hybrid0 (A : Interfaces.Adv_Hybrid0) = {
  proc run(b : bool) : bool = {
    var b' : bool;
    Game_Hybrid0.init(b);
    b' <@ A(Game_Hybrid0).run();
    return b';
  }
}.
