(* Comp_PRF.ec for theorem `Simple4WHS`, composition `PRF` — generated by `domino easycrypt`. *)

require import AllCore Distr FMap Int IntDiv Types.
require Interfaces Pkg_PRF.

clone Pkg_PRF as Cloned_Pkg_PRF.

module Pkg_Inst_PRF = Cloned_Pkg_PRF.PRF.

module Game_PRF : Interfaces.Iface_PRF = {
  var abort_flag : bool

  proc init(b : bool) : unit = {
    abort_flag <- false;
    Pkg_Inst_PRF.init(b);
  }

  proc d_NewKey(ltk : bits_n option) : int option = {
    var ec_result : int option <- None;
    if (!abort_flag) {
      ec_result <@ Pkg_Inst_PRF.d_NewKey(ltk);
      if (ec_result = None) {
        abort_flag <- true;
      }
    }
    return ec_result;
  }

  proc d_Eval(kid : int, x : (int * int * bits_n * bits_n * bool)) : bits_n option = {
    var ec_result : bits_n option <- None;
    if (!abort_flag) {
      ec_result <@ Pkg_Inst_PRF.d_Eval(kid, x);
      if (ec_result = None) {
        abort_flag <- true;
      }
    }
    return ec_result;
  }

  proc d_Hon(kid : int) : bool option = {
    var ec_result : bool option <- None;
    if (!abort_flag) {
      ec_result <@ Pkg_Inst_PRF.d_Hon(kid);
      if (ec_result = None) {
        abort_flag <- true;
      }
    }
    return ec_result;
  }
}.

module Exp_PRF (A : Interfaces.Adv_PRF) = {
  proc run(b : bool) : bool = {
    var b' : bool;
    Game_PRF.init(b);
    b' <@ A(Game_PRF).run();
    return b';
  }
}.
