(* Interfaces.ec for theorem `Simple4WHS` — generated by `domino easycrypt`. *)

require import AllCore FMap Distr Int Types.

(* Iface_Hybrid0/Adv_Hybrid0 also cover: Hybrid1, Hybrid2 *)

module type Iface_Hybrid0 = {
  proc d_NewKey(ltk : bits_n option) : int option
  proc d_NewSession(d_U : int, u : bool, d_V : int, kid : int) : int option
  proc d_Send1(ctr : int) : bits_n option
  proc d_Send2(ctr : int, msg : bits_n) : (bits_n * bits_n) option
  proc d_Send3(ctr : int, msg : (bits_n * bits_n)) : (bits_n * bits_n) option
  proc d_Send4(ctr : int, msg : (bits_n * bits_n)) : bits_n option
  proc d_Send5(ctr : int, msg : bits_n) : bool option
  proc d_Reveal(ctr : int) : bits_n option
  proc d_Test(ctr : int) : bits_n option
}.

module type Adv_Hybrid0 (O : Iface_Hybrid0) = {
  proc run() : bool
}.

module type Iface_PRF = {
  proc d_NewKey(ltk : bits_n option) : int option
  proc d_Eval(kid : int, x : (int * int * bits_n * bits_n * bool)) : bits_n option
  proc d_Hon(kid : int) : bool option
}.

module type Adv_PRF (O : Iface_PRF) = {
  proc run() : bool
}.
