(* Interfaces.ec for theorem `Simple4WHS` — generated by `domino easycrypt`. *)

require import AllCore FMap Distr Int Types.

module type Prot_i = {
  proc d_Run1(state : (int * bool * int * bits_n * bool option * bits_n option * bits_n option * bits_n option * bits_n option * (int * int * bits_n * bits_n * bits_n) option * int)) : ((int * bool * int * bits_n * bool option * bits_n option * bits_n option * bits_n option * bits_n option * (int * int * bits_n * bits_n * bits_n) option * int) * bits_n) option
  proc d_Run2(state : (int * bool * int * bits_n * bool option * bits_n option * bits_n option * bits_n option * bits_n option * (int * int * bits_n * bits_n * bits_n) option * int), ni : bits_n) : ((int * bool * int * bits_n * bool option * bits_n option * bits_n option * bits_n option * bits_n option * (int * int * bits_n * bits_n * bits_n) option * int) * (bits_n * bits_n)) option
  proc d_Run3(state : (int * bool * int * bits_n * bool option * bits_n option * bits_n option * bits_n option * bits_n option * (int * int * bits_n * bits_n * bits_n) option * int), msg : (bits_n * bits_n)) : ((int * bool * int * bits_n * bool option * bits_n option * bits_n option * bits_n option * bits_n option * (int * int * bits_n * bits_n * bits_n) option * int) * (bits_n * bits_n)) option
  proc d_Run4(state : (int * bool * int * bits_n * bool option * bits_n option * bits_n option * bits_n option * bits_n option * (int * int * bits_n * bits_n * bits_n) option * int), msg : (bits_n * bits_n)) : ((int * bool * int * bits_n * bool option * bits_n option * bits_n option * bits_n option * bits_n option * (int * int * bits_n * bits_n * bits_n) option * int) * bits_n) option
  proc d_Run5(state : (int * bool * int * bits_n * bool option * bits_n option * bits_n option * bits_n option * bits_n option * (int * int * bits_n * bits_n * bits_n) option * int), tau : bits_n) : ((int * bool * int * bits_n * bool option * bits_n option * bits_n option * bits_n option * bits_n option * (int * int * bits_n * bits_n * bits_n) option * int) * bool) option
}.

module type KX_i = {
  proc d_NewKey(ltk : bits_n option) : int option
  proc d_NewSession(d_U : int, u : bool, d_V : int, kid : int) : int option
  proc d_Send1(ctr : int) : bits_n option
  proc d_Send2(ctr : int, msg : bits_n) : (bits_n * bits_n) option
  proc d_Send3(ctr : int, msg : (bits_n * bits_n)) : (bits_n * bits_n) option
  proc d_Send4(ctr : int, msg : (bits_n * bits_n)) : bits_n option
  proc d_Send5(ctr : int, msg : bits_n) : bool option
  proc d_Reveal(ctr : int) : bits_n option
  proc d_Test(ctr : int) : bits_n option
  proc d_SameKey(ctr1 : int, ctr2 : int) : bool option
  proc d_AtMost(ctr1 : int, ctr2 : int, ctr3 : int) : bool option
  proc d_AtLeast(sid : (int * int * bits_n * bits_n * bits_n)) : bool option
}.

module type Prot_NoKey_i = {
  proc d_Run1(state : (int * bool * int * bits_n * bool option * bits_n option * bits_n option * bits_n option * (int * int * bits_n * bits_n * bits_n) option * int)) : ((int * bool * int * bits_n * bool option * bits_n option * bits_n option * bits_n option * (int * int * bits_n * bits_n * bits_n) option * int) * bits_n) option
  proc d_Run2(state : (int * bool * int * bits_n * bool option * bits_n option * bits_n option * bits_n option * (int * int * bits_n * bits_n * bits_n) option * int), ni : bits_n) : ((int * bool * int * bits_n * bool option * bits_n option * bits_n option * bits_n option * (int * int * bits_n * bits_n * bits_n) option * int) * (bits_n * bits_n)) option
  proc d_Run3(state : (int * bool * int * bits_n * bool option * bits_n option * bits_n option * bits_n option * (int * int * bits_n * bits_n * bits_n) option * int), msg : (bits_n * bits_n)) : ((int * bool * int * bits_n * bool option * bits_n option * bits_n option * bits_n option * (int * int * bits_n * bits_n * bits_n) option * int) * (bits_n * bits_n)) option
  proc d_Run4(state : (int * bool * int * bits_n * bool option * bits_n option * bits_n option * bits_n option * (int * int * bits_n * bits_n * bits_n) option * int), msg : (bits_n * bits_n)) : ((int * bool * int * bits_n * bool option * bits_n option * bits_n option * bits_n option * (int * int * bits_n * bits_n * bits_n) option * int) * bits_n) option
  proc d_Run5(state : (int * bool * int * bits_n * bool option * bits_n option * bits_n option * bits_n option * (int * int * bits_n * bits_n * bits_n) option * int), tau : bits_n) : ((int * bool * int * bits_n * bool option * bits_n option * bits_n option * bits_n option * (int * int * bits_n * bits_n * bits_n) option * int) * bool) option
}.

module type KX_NoKeys_i = {
  proc d_NewKey(ltk : bits_n option) : int option
  proc d_NewSession(d_U : int, u : bool, d_V : int, kid : int) : int option
  proc d_Send1(ctr : int) : bits_n option
  proc d_Send2(ctr : int, msg : bits_n) : (bits_n * bits_n) option
  proc d_Send3(ctr : int, msg : (bits_n * bits_n)) : (bits_n * bits_n) option
  proc d_Send4(ctr : int, msg : (bits_n * bits_n)) : bits_n option
  proc d_Send5(ctr : int, msg : bits_n) : bool option
  proc d_Reveal(ctr : int) : bits_n option
  proc d_Test(ctr : int) : bits_n option
}.

module type M_PRF_i = {
  proc d_NewKey(ltk : bits_n option) : int option
  proc d_Eval(kid : int, x : (int * int * bits_n * bits_n * bool)) : bits_n option
  proc d_Hon(kid : int) : bool option
}.

module type Prot_NoPrf_i = {
  proc d_Run1(state : (int * bool * int * int * bool option * bits_n option * bits_n option * bits_n option * (int * int * bits_n * bits_n * bits_n) option * int)) : ((int * bool * int * int * bool option * bits_n option * bits_n option * bits_n option * (int * int * bits_n * bits_n * bits_n) option * int) * bits_n) option
  proc d_Run2(state : (int * bool * int * int * bool option * bits_n option * bits_n option * bits_n option * (int * int * bits_n * bits_n * bits_n) option * int), ni : bits_n) : ((int * bool * int * int * bool option * bits_n option * bits_n option * bits_n option * (int * int * bits_n * bits_n * bits_n) option * int) * (bits_n * bits_n)) option
  proc d_Run3(state : (int * bool * int * int * bool option * bits_n option * bits_n option * bits_n option * (int * int * bits_n * bits_n * bits_n) option * int), msg : (bits_n * bits_n)) : ((int * bool * int * int * bool option * bits_n option * bits_n option * bits_n option * (int * int * bits_n * bits_n * bits_n) option * int) * (bits_n * bits_n)) option
  proc d_Run4(state : (int * bool * int * int * bool option * bits_n option * bits_n option * bits_n option * (int * int * bits_n * bits_n * bits_n) option * int), msg : (bits_n * bits_n)) : ((int * bool * int * int * bool option * bits_n option * bits_n option * bits_n option * (int * int * bits_n * bits_n * bits_n) option * int) * bits_n) option
  proc d_Run5(state : (int * bool * int * int * bool option * bits_n option * bits_n option * bits_n option * (int * int * bits_n * bits_n * bits_n) option * int), tau : bits_n) : ((int * bool * int * int * bool option * bits_n option * bits_n option * bits_n option * (int * int * bits_n * bits_n * bits_n) option * int) * bool) option
}.

module type KX_NoPrf_i = {
  proc d_NewSession(d_U : int, u : bool, d_V : int, kid : int) : int option
  proc d_Send1(ctr : int) : bits_n option
  proc d_Send2(ctr : int, msg : bits_n) : (bits_n * bits_n) option
  proc d_Send3(ctr : int, msg : (bits_n * bits_n)) : (bits_n * bits_n) option
  proc d_Send4(ctr : int, msg : (bits_n * bits_n)) : bits_n option
  proc d_Send5(ctr : int, msg : bits_n) : bool option
  proc d_Reveal(ctr : int) : bits_n option
  proc d_Test(ctr : int) : bits_n option
}.

(* Iface_Hybrid0/Adv_Hybrid0 also cover: Hybrid1, Hybrid2 *)

module type Iface_Hybrid0 = {
  proc d_NewKey(ltk : bits_n option) : int option
  proc d_NewSession(d_U : int, u : bool, d_V : int, kid : int) : int option
  proc d_Send1(ctr : int) : bits_n option
  proc d_Send2(ctr : int, msg : bits_n) : (bits_n * bits_n) option
  proc d_Send3(ctr : int, msg : (bits_n * bits_n)) : (bits_n * bits_n) option
  proc d_Send4(ctr : int, msg : (bits_n * bits_n)) : bits_n option
  proc d_Send5(ctr : int, msg : bits_n) : bool option
  proc d_Reveal(ctr : int) : bits_n option
  proc d_Test(ctr : int) : bits_n option
}.

module type Adv_Hybrid0 (O : Iface_Hybrid0) = {
  proc run() : bool
}.

module type Iface_PRF_Game = {
  proc d_NewKey(ltk : bits_n option) : int option
  proc d_Eval(kid : int, x : (int * int * bits_n * bits_n * bool)) : bits_n option
  proc d_Hon(kid : int) : bool option
}.

module type Adv_PRF_Game (O : Iface_PRF_Game) = {
  proc run() : bool
}.
