[package]
name = "domino"
version.workspace = true
edition.workspace = true
readme = { workspace = true }

[dependencies]
sspverif = { workspace = true }
clap = { version = "4.0", features = ["derive"] }
console = "0.16"
env_logger = "0.11"
indicatif = "0.18"
indicatif-log-bridge = "0.2"
miette = { version = "7.6.0", features = ["fancy"] }
shadow-rs = { version = "2", default-features = false }
thiserror = "2"
wildcard = "0.3"

[build-dependencies]
sspverif = { workspace = true }
clap = { version = "4.0", features = ["derive"] }
clap_complete = "*"
shadow-rs = "2"
wildcard = "0.3"
