[package]
name = "domino"
version.workspace = true
edition.workspace = true
readme = { workspace = true }

[dependencies]
sspverif = { workspace = true }
clap = { version = "4.0", features = ["derive"] }
miette = { version = "7.2.0", features = ["fancy"] }
env_logger = "0.11"

[build-dependencies]
sspverif = { workspace = true }
clap = { version = "4.0", features = ["derive"] }
clap_complete = "*"
