name: Run Known-Good Proofs

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  check-proofs:
    runs-on: ubuntu-latest
    name: Check Proofs
    steps:
      - uses: actions/checkout@v2
      - name: Install CVC5
        run: sudo apt install cvc5

      - name: Build ssbee
        run: |
          cargo build --release -p domino
          echo "DOMINO=$(pwd)/target/release/domino">>$GITHUB_ENV

      - name: Run proofs
        run: "./scripts/test-known-examples.sh || exit 1"
