(* Types.ec for theorem `KEM_Proof` — generated by `domino easycrypt`. *)

require import AllCore Distr FMap Int IntDiv.

type bits_256.

op zero_256 : bits_256.

op one_256 : bits_256.

op dbits_256 : bits_256 distr.

axiom dbits_256_ll : is_lossless dbits_256.

op func_decaps : bits_256 -> bits_256 -> bits_256.

op func_encaps : bits_256 -> bits_256 -> (bits_256 * bits_256).

op func_kgen : bits_256 -> bits_256.
